apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
data:
  http-snippet: |
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=my_cache:10m max_size=10g inactive=60m use_temp_path=off;
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_min_length 256;
    gzip_types application/javascript text/css text/plain text/xml application/json application/xml application/rss+xml application/atom+xml image/svg+xml;

    # Buffering Configuration
    proxy_buffer_size 8k;
    proxy_buffers 2048 8k;
    proxy_busy_buffers_size 16k;

    # Timeout Settings
    proxy_read_timeout 60s;
    proxy_send_timeout 60s;
    keepalive_timeout 60s;

    # Enable client IP preservation in the X-Forwarded-For header
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    # Enable SSL Session Cache
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    # Enable HTTP/2 for improved performance
    http2_max_concurrent_streams 64;

    # Tune worker_processes and worker_connections for your hardware
    worker_processes auto;
    worker_connections 2048;

    # Increase the number of open files for Nginx
    worker_rlimit_nofile 8192;

    # Enable TCP optimizations
    tcp_nodelay on;
    tcp_nopush on;
